/-
Copyright (c) 2026 BAIF. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/

import VersoManual
import VersoBlueprint
import VersoManual.Bibliography
import SMDocs.CryptoNotation
import SMDocs.MscDiagram
import SMDocs.CkaFromDdh
import SecureMessaging.CKA.Defs

/-!
# Capability stub: crypto diagrams (protocol flow + security game)

Two figures from the CKA literature, drawn *natively* in the documentation rather
than pasted as images:

* a two-party **protocol flow** (message-sequence chart), via the data-driven
  `:::msc` block extension; and
* the **security game**, typeset entirely in KaTeX with the cryptocode-style macros
  from `SMDocs.CryptoNotation` (procedure boxes, colour-coded oracle headers, a
  boxed advantage definition).

Both stay editable source — change the `Msc` data value or the math and the page
re-renders. The game's oracles are the real `SecureMessaging` declarations
(`CKAScheme.securityExp`, `CKAScheme.oracleSendA`, …); the `#check` blocks and the
`(lean := "…")` blueprint refs resolve against the live library, so a rename fails
the build instead of letting the figure drift from the formalisation.
-/

open Verso.Genre Manual
open Informal

set_option doc.verso true

#doc (Manual) "CKA Protocol Flow and Security Game" =>
%%%
tag := "cka_diagrams"
%%%

The continuous key agreement (CKA) of {Informal.citet ACD19}[] is usually presented
with two pictures: a _protocol flow_ showing the two parties ratcheting, and a
_security game_ defining the oracles an adversary may call. Both are reproduced
below as editable documentation — the flow from a small data value, the game from
KaTeX. The syntax and security model follow {Informal.citet TripleRatchet}[]
(Definition 2.12 / 2.13).

# Protocol flow

Alice and Bob alternate. Each `Send` samples a fresh epoch key (shown as a blue
chip) and emits a message $`\rho_i`; the peer's matching `Rec` _derives_ the same
key (red chip). The green chips are the `CKAScheme` algorithms — `initA`, `sendA`,
`recvB`, and so on. The whole chart is a single `Msc` data value rendered by the
`:::msc` block:

:::msc
:::

:::definition "cka_protocol"
{uses "cka_interface"}[]
The CKA _ping-pong_: party A and party B alternate sending and receiving, and every
message $`\rho_i` advances a shared epoch key $`K_i`. Key $`K_i` is generated by one
party's send and derived by the other party's receive, so both sides agree on the
sequence $`K_1, K_2, K_3, \dots` of epoch keys.
:::

# The security game

The game of {Informal.citet ACD19}[] (Definition 13) gives the adversary three
families of oracles — _communication_ (black), _corruption_ (red), and _challenge_
(blue):

$$`\hdrK{\text{communication oracles}} \quad \hdrR{\text{corruption oracles}} \quad \hdrB{\text{challenge oracles}}`

Each oracle is a procedure box (`\proc`): a coloured header, a rule, then its
pseudocode body. This entire grid is KaTeX — no image, no LaTeX package:

$$`
\begin{array}{lll}
\proc{\hdrK{\orc{O-Init}}\,(t^*)}{
  I_{CKA} \sample \KeyGen(1^\lambda) \\
  st_A \getsval \orc{Init-A}(I_{CKA}) \\
  st_B \getsval \orc{Init-B}(I_{CKA}) \\
  t_A, t_B \getsval 0 \\
  b \sample \bit
}
&
\proc{\hdrK{\orc{O-Send-A}}}{
  t_A \pp \\
  (K_{t_A}, \rho_{t_A}, st_A) \sample \orc{Send-A}(st_A) \\
  \Return (\rho_{t_A}, K_{t_A})
}
&
\proc{\hdrK{\orc{O-Send-B}}}{
  t_B \pp \\
  (K_{t_B}, \rho_{t_B}, st_B) \sample \orc{Send-B}(st_B) \\
  \Return (\rho_{t_B}, K_{t_B})
}
\\[1.4em]
\proc{\hdrR{\orc{O-Corr-A}}}{
  \req \orc{allow-corr} \vee \orc{finished}_A \\
  \Return st_A
}
&
\proc{\hdrK{\orc{O-Rec-A}}}{
  t_A \pp \\
  (K_{t_A}, st_A) \getsval \orc{Rec-A}(st_A, \rho_{t_A})
}
&
\proc{\hdrK{\orc{O-Rec-B}}}{
  t_B \pp \\
  (K_{t_B}, st_B) \getsval \orc{Rec-B}(st_B, \rho_{t_B})
}
\\[1.4em]
\proc{\hdrR{\orc{O-Corr-B}}}{
  \req \orc{allow-corr} \vee \orc{finished}_B \\
  \Return st_B
}
&
\proc{\hdrB{\orc{O-Chall-A}}}{
  t_A \pp \\
  \req t_A = t^* \\
  (K_{t_A}, \rho_{t_A}, st_A) \sample \orc{Send-A}(st_A) \\
  \textbf{if } b = 0:\ \Return (\rho_{t_A}, K_{t_A}) \\
  \textbf{else}:\ K \sample \mathcal{K};\ \Return (\rho_{t_A}, K)
}
&
\proc{\hdrB{\orc{O-Chall-B}}}{
  t_B \pp \\
  \req t_B = t^* \\
  (K_{t_B}, \rho_{t_B}, st_B) \sample \orc{Send-B}(st_B) \\
  \textbf{if } b = 0:\ \Return (\rho_{t_B}, K_{t_B}) \\
  \textbf{else}:\ K \sample \mathcal{K};\ \Return (\rho_{t_B}, K)
}
\\[1.4em]
\proc{\hdrR{\orc{Win}}_{\mathcal{A}}}{
  b' \getsval \mathcal{A}^{\mathcal{O}} \\
  \Return (b' = b)
}
& &
\end{array}
`

The oracle bodies are not decorative: each is a real `SecureMessaging`
declaration. Hover the `#check`s below to read their types off the live library:

```lean "sig_security_game"
#check @CKAScheme.securityExp
#check @CKAScheme.ckaGuessAdvantage
```

:::definition "cka_oracles" (lean := "CKAScheme.oracleSendA, CKAScheme.oracleRecvA, CKAScheme.oracleChallA, CKAScheme.oracleCorruptA")
{uses "cka_protocol"}[]
The send/receive oracles (`oracleSendA` / `oracleRecvA` and their `B` duals) drive
the protocol; the challenge oracles (`oracleChallA` / `oracleChallB`) return either
the real epoch key (when the secret bit $`b = 0`) or a uniformly random key; the
corruption oracles (`oracleCorruptA` / `oracleCorruptB`) leak a party's state when
the freshness gate permits.
:::

# Advantage

The two predicates gating corruption: a party may be corrupted only outside the
$`\Delta`-window around the challenge epoch $`t^*`:

$$`\orc{allow-corr} :\Longleftrightarrow \max(t_A, t_B) \le t^* - 2 \qquad \orc{finished}_P :\Longleftrightarrow t_P \ge t^* + \Delta_{CKA}`

CKA security bounds every adversary in a class $`\mathcal{C}` to a negligible
distinguishing advantage:

$$`\secdef{
  \textbf{CKA Security against class } \mathcal{C}: \\[0.3em]
  \forall\, \mathcal{A} \in \mathcal{C}.\quad \bigl|\Pr[\orc{Win}_{\mathcal{A}} = 1] - \tfrac{1}{2}\bigr| \le \varepsilon
}`

:::theorem "cka_advantage" (lean := "CKAScheme.ckaGuessAdvantage")
{uses "cka_oracles"}[]
The guessing advantage `CKAScheme.ckaGuessAdvantage` is exactly
$`\bigl|\Pr[\,\mathsf{securityExp} = \mathsf{true}\,] - \tfrac{1}{2}\bigr|`; a scheme
is secure against a class $`\mathcal{C}` when this quantity is at most
$`\varepsilon` for every $`\mathcal{A} \in \mathcal{C}` and every choice of game
parameters.
:::
