name = "SecureMessagingDocs"
defaultTargets = ["SecureMessagingDocs"]

[[require]]
name = "versoBlueprint"
git = "https://github.com/leanprover/verso-blueprint"
rev = "6920b27f7af8dd57ff3114067ab656313eaee082"

[[require]]
name = "SecureMessaging"
path = ".."

[[lean_lib]]
name = "SecureMessagingDocs"

[[lean_exe]]
name = "docs"
root = "Main"
