name = "SecureMessagingDocs"
defaultTargets = ["SecureMessagingDocs", "docs"]

[[require]]
name = "versoBlueprint"
git = "https://github.com/leanprover/verso-blueprint"
rev = "v4.29.0"

[[require]]
name = "SecureMessaging"
path = ".."

[[lean_lib]]
name = "SecureMessagingDocs"

[[lean_exe]]
name = "docs"
root = "Main"
