/-
Copyright (c) 2026 Beneficial AI Foundation. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Beneficial AI Foundation
-/

import SecureMessaging.SCKA.OppUniKEM.Security.Reduction.HybridGame

/-!
# The selected online sample is used once

**Use condition.** An ordinary B-send uses the selected online sample when
B is in epoch `e`, has its public key and offline acknowledgement, and is
ready for fresh online encapsulation. A leaking B-send additionally requires
`e` to be unchallenged; its exposure guard otherwise rejects the sample.

**State facts.** Once B's table contains a key at `e`, every security query
preserves that entry's availability. Transcript consistency then excludes
another fresh online encapsulation at `e`. These facts provide the used-state
predicate for deferring the selected online sample.
-/

open OracleSpec OracleComp KEMScheme

namespace oppUniKemCKA.Security.Embedding

variable {K PK SK C Sym : Type}

/-- B's next send reaches online encapsulation: its acknowledgement and
public key are present, its online ciphertext is absent, and its offline
state is either present or generated by this send. -/
abbrev onlineReady {base : KEMScheme ProbComp K PK SK C} {onoff : base.OnOffStructure}
    (s : StB onoff Sym) : Prop :=
  s.ack.ctRec = true ∧ s.ekA.isSome ∧ s.ct1.isNone ∧
    (s.ct0.isNone ∨ s.stCt.isSome)

/-- Whether query `t` uses the selected online sample from state `s`.
Ordinary B-sends use it at online completion; leaking B-sends use it when
the same completion passes the selected-epoch challenge guard. -/
def usesOnline {base : KEMScheme ProbComp K PK SK C} {onoff : base.OnOffStructure}
    {leak : base.OnOffRandLeak onoff} (e : ℕ) (t : (securitySpec leak Sym).Domain)
    (s : SCKAScheme.GameState (StA onoff Sym) (StB onoff Sym) K (Message Sym)) : Bool :=
  match t with
  | .inl (.inl (.inl (.inl (.inl (.inl (.inl (.inr ()))))))) =>
    decide (s.stB.t = e ∧ onlineReady s.stB)
  | .inl (.inl (.inl (.inr ()))) =>
    decide ((s.stB.t = e ∧ onlineReady s.stB) ∧ e ∉ s.challenged)
  | _ => false

/-- In every transcript-consistent state where B has a recorded key at
`e`, every query has `usesOnline e = false`. A fresh online ciphertext and
a previously recorded key at the same epoch are incompatible. -/
theorem usesOnline_eq_false_of_recorded
    (base : KEMScheme ProbComp K PK SK C) (onoff : base.OnOffStructure)
    (ecEk : ErasureCodePayload PK Sym)
    (ecCt0 : ErasureCodePayload onoff.C₀ Sym)
    (ecCt1 : ErasureCodePayload onoff.C₁ Sym) (leak : base.OnOffRandLeak onoff)
    (e : ℕ) (t : (securitySpec leak Sym).Domain)
    (s : SCKAScheme.GameState (StA onoff Sym) (StB onoff Sym) K (Message Sym))
    (hs : reachableInv base onoff ecEk ecCt0 ecCt1 s) (hk : (s.keyB e).isSome) :
    usesOnline e t s = false := by
  have hnot : ¬(s.stB.t = e ∧ onlineReady s.stB) := by
    rintro ⟨he, hready⟩
    have hct : s.stB.ct1 = none := Option.isNone_iff_eq_none.mp hready.2.2.1
    have hnone := (keys_none_before_online base onoff ecEk ecCt0 ecCt1 s hs hct).2
    rw [he] at hnone
    simp only [hnone, Option.isSome_none, Bool.false_eq_true] at hk
  rcases t with (((((t | u) | u) | t) | u) | u)
  · rcases t with ((((n | u) | u) | n) | n) <;> simp [usesOnline, hnot]
  all_goals simp [usesOnline, hnot]

/-- For every material value, epoch, mode, and query, the pinned hybrid
preserves availability of B's previously recorded key at `e`. -/
theorem hybridOracle_preserves_keyB_available
    [DecidableEq K] [DecidableEq Sym] [SampleableType K]
    (base : KEMScheme ProbComp K PK SK C) (onoff : base.OnOffStructure)
    (ecEk : ErasureCodePayload PK Sym)
    (ecCt0 : ErasureCodePayload onoff.C₀ Sym)
    (ecCt1 : ErasureCodePayload onoff.C₁ Sym) (leak : base.OnOffRandLeak onoff)
    (m : Material leak) (e : ℕ) (b : Bool) :
    QueryImpl.PreservesInv (hybridOracle base onoff ecEk ecCt0 ecCt1 leak m e b)
      (fun s => (s.keyB e).isSome) := by
  intro t s hs z hz
  rcases t with (((((t | u) | u) | t) | u) | u)
  · exact SCKAScheme.correctnessImpl_preserves_keyB_available
      (honestScheme ecEk ecCt0 ecCt1 m e s) e t s hs z hz
  · cases u
    apply SCKAScheme.oracleSendArleak_preservesInv_at
      (honestScheme ecEk ecCt0 ecCt1 m e s) sendExposureA _
      (fun s => (s.keyB e).isSome) (fun _ _ h => h) s hs _ z hz
    · exact sendArleak_forget _ _ _ _
    · exact SCKAScheme.correctnessImpl_preserves_keyB_available
        (honestScheme ecEk ecCt0 ecCt1 m e s) e SCKAScheme.sckaCorrectnessSpec.OSendA s hs
  · cases u
    apply SCKAScheme.oracleSendBrleak_preservesInv_at
      (honestScheme ecEk ecCt0 ecCt1 m e s) sendExposureB _
      (fun s => (s.keyB e).isSome) (fun _ _ h => h) s hs _ z hz
    · exact sendBrleak_forget _ _ _ _ _
    · exact SCKAScheme.correctnessImpl_preserves_keyB_available
        (honestScheme ecEk ecCt0 ecCt1 m e s) e SCKAScheme.sckaCorrectnessSpec.OSendB s hs
  · exact SCKAScheme.oracleChall_preservesInv (adjacentMode e b t)
      (fun s => (s.keyB e).isSome) (fun _ _ h => h) t s hs z hz
  · exact SCKAScheme.oracleCorruptA_preservesInv (vulnA base onoff)
      (fun s => (s.keyB e).isSome) (fun _ _ h => h) u s hs z hz
  · exact SCKAScheme.oracleCorruptB_preservesInv (vulnB base onoff)
      (fun s => (s.keyB e).isSome) (fun _ _ h => h) u s hs z hz

/-- Assume supported material, deterministic decapsulation, and correct
erasure codes. Every query of either pinned hybrid preserves the conjunction
of the original transcript invariant and the selected source invariant. -/
theorem hybridOracle_preserves_simulationInv
    [DecidableEq K] [DecidableEq Sym] [SampleableType K]
    (base : KEMScheme ProbComp K PK SK C) (onoff : base.OnOffStructure)
    (hDet : base.DeterministicDecaps)
    (ecEk : ErasureCodePayload PK Sym) (hEk : ecEk.ec.Correct)
    (ecCt0 : ErasureCodePayload onoff.C₀ Sym) (hCt0 : ecCt0.ec.Correct)
    (ecCt1 : ErasureCodePayload onoff.C₁ Sym) (hCt1 : ecCt1.ec.Correct)
    (leak : base.OnOffRandLeak onoff)
    (m : Material leak) (hm : m ∈ support (sampleMaterial leak)) (e : ℕ) (b : Bool) :
    QueryImpl.PreservesInv (hybridOracle base onoff ecEk ecCt0 ecCt1 leak m e b)
      (fun s => reachableInv base onoff ecEk ecCt0 ecCt1 s ∧ pinnedSources m e s) := by
  intro t s hs z hz
  rcases t with (((((t | u) | u) | t) | u) | u)
  all_goals
    first
    | exact honestOracle_preserves_simulationInv base onoff hDet ecEk hEk ecCt0 hCt0
        ecCt1 hCt1 leak m hm e m.on.1.2 _ s hs z hz
    | apply SCKAScheme.oracleChall_preservesInv (adjacentMode e b t)
        (fun s => reachableInv base onoff ecEk ecCt0 ecCt1 s ∧ pinnedSources m e s)
        _ t s hs z hz
      intro s challenged hs
      exact ⟨reachableInv_with_security_bookkeeping hs.1 s.exposed challenged, hs.2⟩

end oppUniKemCKA.Security.Embedding
